### ISSUE TITLE
Kotlintest test classes are excluded from test running 

### ISSUE THREAD

**Issue by adamkobor** [micronaut-projects/micronaut-test#68] opened 2019-08-08 11:16 UTC
If we write a test class with kotlintest without injecting any Micronaut related stuff into the class' constructor, the test class will be totally ignored in test running.

Example repo: https://github.com/adamkobor/micronaut-kotlintest-bug

## Example test classes

Working:
```kotlin
@MicronautTest
class IncludedExampleControllerSpec(@Client("/") private val client: RxHttpClient) : BehaviorSpec() {

    init {
        given("an index endpoint") {
            `when`("called") {
                val resp = client.toBlocking().exchange<Any>("/")
                then("the response should be OK") {
                    resp.status.shouldBe(HttpStatus.OK)
                }
            }
        }
    }
}
```

Ignored:
```kotlin
@MicronautTest
class ExcludedExampleControllerSpec : BehaviorSpec() {

    private val client = startTestApplication().getLowLevelClient()

    init {
        given("the index endpoint") {
            `when`("called") {
                val resp = client.toBlocking().exchange<Any>("/")
                then("the response should be OK") {
                    resp.status.shouldBe(HttpStatus.OK)
                }
            }
        }
    }
}

fun startTestApplication(): EmbeddedServer =
    ApplicationContext
        .build()
        .build()
        .start()
        .getBean(EmbeddedServer::class.java)
        .start()

fun EmbeddedServer.getLowLevelClient(): RxHttpClient =
    this.applicationContext.createBean(RxHttpClient::class.java, this.url)
```

When we run the `test` Gradle task, only `IncludedExampleControllerSpec` will be included in the process.

**Comment by otbe** [comment] 2019-09-22 18:20
A related problem (because the same code procudes it) is that we cant run non-micronaut tests. For example:

```
class SimplerTest : AnnotationSpec() {
    @Test
    fun foo() {
        1 shouldBe 1
    }
}

```

produces
```
20:20:22.819 [main] ERROR io.kotlintest.runner.jvm.TestEnginejava.lang.IllegalStateException: micronautTest must not be null
 - Error during test engine run
java.lang.IllegalStateException: micronautTest must not be null
	at io.micronaut.test.extensions.kotlintest.MicronautKotlinTestExtension.instantiate(MicronautKotlinTestExtension.kt:52)
	at io.micronaut.test.extensions.kotlintest.MicronautKotlinTestExtension.instantiate(MicronautKotlinTestExtension.kt:52)
	at io.kotlintest.runner.jvm.JvmKt.instantiateSpec(jvm.kt:14)
	at io.kotlintest.runner.jvm.JvmKt.instantiateSpec(jvm.kt:14)
	at io.kotlintest.runner.jvm.TestEngine.createSpec(TestEngine.kt:112)
	at io.kotlintest.runner.jvm.TestEngine.createSpec(TestEngine.kt:112)
	at io.kotlintest.runner.jvm.TestEngine.access$createSpec(TestEngine.kt:15)
	at io.kotlintest.runner.jvm.TestEngine.access$createSpec(TestEngine.kt:15)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:91)
	at io.kotlintest.runner.jvm.TestEngine$submitSpec$1.run(TestEngine.kt:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by logistark** [comment] 2019-10-29 13:24
For what i am reading in the code of the extension, this maybe the origin of this behaviour:

In line 49 of MicronautKotlintTestExtension.kt
```
       return if (constructor == null || constructor.parameters.isEmpty() && micronautTest != null) {
            null
        } else {
            val context = MicronautKotlinTestContext(testClass, micronautTest)
            val bean: Spec = context.bean
            contexts[bean] = context
            bean
        }
```

If you notice the case that is working is the one with a parameter in the class, that counts as a constructor parameter. The second case if you add a dummy parameter to the class should work. And for the behaviour that point @otbe is pointing it seems have the same origin. I don't clearly understand for what reason is this condition.

**Comment by logistark** [comment] 2019-10-29 14:03
It seems that this have a bad interaction with another part of the extension. Because returning null is the expected behaviour for `instantiate` method as is documented in KotlinTest.

```
        if (context?.getSpecDefinition() == null) {
            complete(TestResult.Ignored)
        } else {
            execute(testCase, complete)
        }
```

Seems that the intercept method that is implemented before is marking as ignored the test cases that `instantiate`return as null

**Closed** 2019-10-29 18:22 UTC
Labels: bug
