### ISSUE TITLE
More than 1 test class with inherited @MockBean definitions fails to initialize

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-test#223] opened 2020-07-22 23:25 UTC
This simple example fails when there is more than 1 test class inheriting shared bean definitions, this is basically the same as an existing `micronaut-test` test case but with 2 subclasses rather than 1.  (https://github.com/micronaut-projects/micronaut-test/blob/master/test-junit5/src/test/java/io/micronaut/test/junit5/MathCollaboratorBaseTest.java)

simple bean and dependency

```java
import javax.inject.Singleton;

@Singleton
public class MathService {

    private MathWorker worker;

    public MathService(MathWorker worker) {
        this.worker = worker;
    }

    public MathWorker getWorker() {
        return worker;
    }
}
```

dependent:

```java
import javax.inject.Singleton;

@Singleton
public class MathWorker {

}
```

with a simple test:

```java
import io.micronaut.test.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

@MicronautTest
class FirstMathServiceTest extends MathServiceTestBase {

    @Inject MathService mathService;

    @Test
    void testComputeNumToSquare() {
        assertNotNull(mathService);
    }

}
```

this works, but if we add a second test same as the first, extending from the same base it fails BOTH tests fail:

```java
import io.micronaut.test.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@MicronautTest
class SecondMathServiceTest extends MathServiceTestBase {

    @Inject MathService mathService;

    @Test
    void testComputeNumToSquare() {
        assertNotNull(mathService);
    }

}
```

```
2020-07-23 09:14:01:365       main DEBUG t.DefaultBeanContext -                           - Finding candidate beans for instance: test.FirstMathServiceTest@34cf5a97
2020-07-23 09:14:01:366       main TRACE t.DefaultBeanContext -                           - Looking up existing bean for key: test.MathService
2020-07-23 09:14:01:366       main TRACE t.DefaultBeanContext -                           - No existing bean found for bean key: test.MathService
2020-07-23 09:14:01:366       main DEBUG t.DefaultBeanContext -                           - Finding candidate beans for type: class test.MathService
2020-07-23 09:14:01:367       main DEBUG t.DefaultBeanContext -                           - Resolved bean candidates [Definition: test.MathService] for type: class test.MathService
2020-07-23 09:14:01:367       main DEBUG t.DefaultBeanContext -                           - Finalized bean definitions candidates: [Definition: test.MathService]
2020-07-23 09:14:01:367       main DEBUG t.DefaultBeanContext -                           - Found concrete candidate [Definition: test.MathService] for type: test.MathService 
2020-07-23 09:14:01:367       main TRACE t.DefaultBeanContext -                           - Looking up existing bean for key: test.MathWorker
2020-07-23 09:14:01:367       main TRACE t.DefaultBeanContext -                           - No existing bean found for bean key: test.MathWorker
2020-07-23 09:14:01:367       main DEBUG t.DefaultBeanContext -                           - Finding candidate beans for type: class test.MathWorker
2020-07-23 09:14:01:367       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:368       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:368       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:368       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:368       main DEBUG .condition.Condition -                           - Bean [Definition: test.$SecondMathServiceTest$MathWorker0Definition$Intercepted] will not be loaded due to failing conditions:
2020-07-23 09:14:01:368       main DEBUG .condition.Condition -                           - * Custom condition [class io.micronaut.test.condition.TestActiveCondition] failed evaluation
2020-07-23 09:14:01:369       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:369       main DEBUG t.DefaultBeanContext -                           - Bean [class test.MathWorker] replaces existing bean of type [class test.MathWorker]
2020-07-23 09:14:01:369       main TRACE urcePropertyResolver -                           - Resolved value [class test.FirstMathServiceTest] for property: micronaut.test.active.spec.clazz
2020-07-23 09:14:01:369       main DEBUG t.DefaultBeanContext -                           - Bean [class test.$FirstMathServiceTest$MathWorker0Definition$Intercepted] replaces existing bean of type [class test.MathWorker]
2020-07-23 09:14:01:369       main DEBUG t.DefaultBeanContext -                           - Bean [class test.$FirstMathServiceTest$MathWorker0Definition$Intercepted] replaces existing bean of type [class test.MathWorker]
2020-07-23 09:14:01:369       main DEBUG t.DefaultBeanContext -                           - Resolved bean candidates [] for type: class test.MathWorker
2020-07-23 09:14:01:371       main DEBUG t.DefaultBeanContext -                           - Resolving beans for type: io.micronaut.test.context.TestExecutionListener
2020-07-23 09:14:01:372       main TRACE t.DefaultBeanContext -                           - Looking up existing beans for key: io.micronaut.test.context.TestExecutionListener
2020-07-23 09:14:01:372       main TRACE t.DefaultBeanContext -                           - Found 0 existing beans for type [io.micronaut.test.context.TestExecutionListener]: [] 


io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [worker] of class: test.MathService

Message: No bean of type [test.MathWorker] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: FirstMathServiceTest.mathService --> new MathService([MathWorker worker])

	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1057)
	at test.$MathServiceDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1888)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2630)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2616)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2299)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2273)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1233)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1465)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1225)
	at test.$FirstMathServiceTestDefinition.injectBean(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.inject(AbstractBeanDefinition.java:359)
	at io.micronaut.context.DefaultBeanContext.doInject(DefaultBeanContext.java:2144)
	at io.micronaut.context.DefaultBeanContext.inject(DefaultBeanContext.java:783)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeEach(AbstractMicronautExtension.java:263)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeEach(MicronautJunit5Extension.java:78)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:160)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [test.MathWorker] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1233)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1035)
	... 62 more

```

My guess would be since the first and second class share a bean definition, when running the first test the TestActiveCondition is excluding beans that are defined in the second test class, but since the definition is shared it fails, and subsequently when you run the second test it fails for the same reason, it is excluding beans from the first (still shared!).

I haven't found a workaround to this yet, other than duplicating shared definitions everywhere, as per other issues since ~@MicronautTest is a factory, we can't use a separate shared @Factory either..

### Environment Information

- **Operating System**: macOS 10.15
- **Micronaut Version:** 2.0.0, test version 1.2.2
- **JDK Version:** JDK 14.0.1

**Comment by alvarosanchez** [comment] 2020-08-25 17:23
This issue is in reality a duplicate of #123 and #20 

Commit 1370daf demonstrates that the problem is that the service doesn't implement any interface

**Comment by asodja** [comment] 2020-09-13 14:22
@alvarosanchez I think this one was incorrectly closed. 

This change: https://github.com/asodja/micronaut-test/commit/5d39183ef766c7320251ebe72aba492bf066eb18 shows that `SimpleService` is not mocked in provided test. And after changing: `@Inject SimpleService simpleService`  to `@Inject SimpleServiceInterface simpleService` one gets:
```
Message: Circular dependency detected
Path Taken: 
Simple2Test.simpleService
^                      |
|                      |
|                      |
+----------------------+
````

I created another test that shows that mocking fails with more than 1 test class extending same base: https://github.com/asodja/micronaut-test/commit/a1fabead8290d6f83a41e17ff814c77807d3133d. 
In that case one will get: `io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found... `

**Comment by asodja** [comment] 2020-09-26 10:12
I found a workaround for inheritance issue: you have to use `@Factory` and not `@MockBean` in super class. 

Example: https://github.com/asodja/micronaut-test/commit/9de1cacec1891543e9f28b3b25b1384dafb27439. 

I use also `@Requires` with some condition for Factory, so mocks are enabled only for tests with those conditions: in my case I added that `@Factory` is enabled only when env `enable-simple-inheritence-mocks` is set.

Note1: I moved `@MicronautTest` annotation to base class, so it's harder to forget to set env.
Note2: I you add new `@MicronautTest` on implementation classes, then it overrides `@MicronautTest` on base class.
Note3: In implementation class you can override mocks with adding `@Primary` annotation. 
Example:
```
@Primary
@MockBean(SimpleService.class)
SimpleServiceInterface simpleService() {
     return new MyAnotherSimpleService();
}
```

I hope this helps.

**Closed** 2020-10-05 16:27 UTC
Labels: status: awaiting validation
