### ISSUE TITLE
[micronaut-test-core] transactional support for multi datasource

### ISSUE THREAD

**Issue by wbprime** [micronaut-projects/micronaut-test#359] opened 2020-12-17 04:45 UTC
Annotation `io.micronaut.test.extensions.junit5.annotation.MicronautTest` has a field `boolean transactional() default true;`, which would trigger `io.micronaut.test.transaction.TestTransactionInterceptorListener` to do simple transaction related hooking jobs.

When dealing with multi-datasource cases, what the semantics meaning of test transactional support, i.e., for which datasource ?

Currently "Transaction synchronization is not active" exception would thrown for tests for mult-datasource cases:

```
java.lang.IllegalStateException: Transaction synchronization is not active

	at io.micronaut.transaction.support.TransactionSynchronizationManager.getSynchronizations(TransactionSynchronizationManager.java:333)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.triggerAfterCompletion(AbstractSynchronousTransactionManager.java:1027)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.processRollback(AbstractSynchronousTransactionManager.java:937)
	at io.micronaut.transaction.support.AbstractSynchronousTransactionManager.rollback(AbstractSynchronousTransactionManager.java:889)
	at io.micronaut.transaction.test.DefaultTestTransactionExecutionListener.afterTestExecution(DefaultTestTransactionExecutionListener.java:95)
	at io.micronaut.transaction.test.DefaultTestTransactionExecutionListener.afterTestExecution(DefaultTestTransactionExecutionListener.java:82)
	at io.micronaut.test.extensions.AbstractMicronautExtension.fireListeners
```

**Comment by jameskleeh** [comment] 2021-03-26 17:51
Duplicate of #95

**Closed by jameskleeh** 2021-03-26 17:51 UTC
