### ISSUE TITLE
Compatibility with kotest 4.2.3

### ISSUE THREAD

**Issue by elijah-trexler** [micronaut-projects/micronaut-test#281] opened 2020-09-10 21:06 UTC
### Steps to Reproduce
1. With the following in your `build.gradle`:
* `testImplementation("io.micronaut.test:micronaut-test-kotest:1.2.3")`
* `testImplementation("io.kotest:kotest-runner-junit5:4.1.3")`

run tests (`./gradlew test`) using the `@MicronautTest` annotation for tests backed by `kotest`. Confirm tests run as expected

2. Change the version of `io.micronaut.test:micronaut-test-kotest` to `4.2.3` and rerun tests

### Expected Behaviour

Tests run with same results between kotest versions

### Actual Behaviour

All tests will fail with 
```java.lang.AbstractMethodError: Receiver class io.micronaut.test.extensions.kotest.MicronautKotestExtension does not define or inherit an implementation of the resolved method 'abstract java.lang.Object beforeEach(io.kotest.core.test.TestCase, kotlin.coroutines.Continuation)' of interface io.kotest.core.listeners.TestListener```

### Environment Information

- **Operating System**: macOS Mojave 10.14.6
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

### Example Application

- https://github.com/elijah-trexler/micro-kotest-version

### Other information

This looks to be caused by: https://github.com/kotest/kotest/pull/1589 which updates the `TestListener` interface. This is not yet reflected in `micronaut-test`: https://github.com/micronaut-projects/micronaut-test/blob/master/test-kotest/src/main/kotlin/io/micronaut/test/extensions/kotest/MicronautKotestExtension.kt

**Comment by codingdiscer** [comment] 2020-09-17 19:26
@ilopmar  - i'm afraid that PR #293 is flawed because it didn't address the problem that is identified in this issue.  

I verified this myself with the latest version `2.0.0` of this release (`io.micronaut.test:micronaut-test-kotest`), and it still fails with the same error message that is shared by the OP.

**Comment by jameskleeh** [comment] 2020-09-17 20:11
@codingdiscer As you can see here https://github.com/micronaut-projects/micronaut-test/runs/1129440642#step:7:1093 the tests passed with the new kotest version. Are you certain you tested with the changes from the PR applied?

**Comment by codingdiscer** [comment] 2020-09-17 20:39
@jameskleeh - after pulling down `2.1.0.BUILD-SNAPSHOT`, my tests now work as expected, and that allows me to upgrade the other dependencies that I was hoping to use.  

thank you much for pointing me in the right direction.  i'll watch for the `2.1.x` release so I can remove the dependency on the snapshot - not a big deal at the moment in my development cycle.

**Comment by jameskleeh** [comment] 2020-09-17 20:40
@codingdiscer Thanks for trying it out! I'll go ahead and close this issue since it is now resolved.

**Closed by jameskleeh** 2020-09-17 20:40 UTC
Labels: type: dependency-upgrade, type: improvement

**Comment by ilopmar** [comment] 2020-09-18 07:47
@codingdiscer I'm just about to release release Micronaut Test 2.1.0.M1 because we also need it for Starter project. Then I'll merge a few pending PRs and upgrade some dependencies before GA version.

**Comment by ilopmar** [comment] 2020-09-18 08:27
@codingdiscer please try now with `2.1.0.M1`

**Comment by codingdiscer** [comment] 2020-09-18 14:13
I can confirm that release `2.1.0.M1` continues to work as expected.  Good to go!
